In [1]:
import numpy as np

In [2]:
A = np.array([[.5,.3,0],[.4,.5,.5],[.1,.2,.5]])

In [3]:
A

array([[0.5, 0.3, 0. ],
       [0.4, 0.5, 0.5],
       [0.1, 0.2, 0.5]])

In [4]:
v0 = np.array([[1],[0],[0]])
v0

array([[1],
       [0],
       [0]])

In [11]:
v2 = np.linalg.matrix_power(A,2)@v0
v2

array([[0.37],
       [0.45],
       [0.18]])

In [15]:
evals,evecs = np.linalg.eig(A)
print('Eigenvalues')
print(evals)
print()
print('Eigenvectors')
print(evecs)

Eigenvalues
[1.         0.43027756 0.06972244]

Eigenvectors
[[-0.46989862 -0.78010553  0.55506939]
 [-0.78316436  0.18130286 -0.79611302]
 [-0.40724547  0.59880267  0.24104363]]


In [22]:
# Select the target eigenvector
v = evecs[:,0]

# Make it stochastic
v = v/sum(v)
print(v)

[0.28301887 0.47169811 0.24528302]
