<a href="https://colab.research.google.com/github/wesmith4/mat210/blob/main/hw1/Ross_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Initiate arrival times and service times
arrival_times = np.array([12,31,63,95,99,154,198,221,304,346,411,455,537])
service_times = np.array([40,32,55,48,18,50,47,18,28,54,40,72,12])
departure_timesA = np.zeros_like(arrival_times, dtype=int)
departure_timesB = np.zeros_like(arrival_times,dtype=int)
departure_timesC = np.zeros_like(arrival_times,dtype=int)

In [ ]:
available = True
clock = 0
currentTaskTime = -1
currentCustomer = -1
served = arrival_times == 0 # logical array for served / not served
finished = False
backlog = np.zeros_like(service_times, dtype=int)
wait_times = np.ones_like(arrival_times) * -1

while not finished:
  clock += 1 # Process tick on the clock
  if currentTaskTime > 0:
    currentTaskTime -= 1
  if currentTaskTime == 0:
    served[currentCustomer] = True
    print('Customer {} has been served at {}'.format(currentCustomer,clock))
    departure_timesA[currentCustomer] = clock

    if np.count_nonzero(backlog) > 0:
      currentCustomer = np.argmax(wait_times)
      currentTaskTime = backlog[currentCustomer]
      # print('Initiated Task #{} ({}) at time {}'.format(currentCustomer, currentTaskTime, clock))
      wait_times[currentCustomer] = -1
      backlog[currentCustomer] = 0

    else:
      currentCustomer = -1
      currentTaskTime = -1
      available = True

  # Handle arrivals
  for customer in range(13):
    if clock == arrival_times[customer]:
      # print('Customer {} arrived at {}'.format(customer,clock))
      if available:
        currentCustomer = customer
        currentTaskTime = service_times[customer]
        # print('Initiated Task #{} ({}) at time {}'.format(currentCustomer, currentTaskTime, clock))
        available = False
      else:
        backlog[customer] = service_times[customer] # Add their service to the backlog
        wait_times[customer] = 0 # Initiate their waiting process
    

    if wait_times[customer] >= 0: # handle waiting
      wait_times[customer] += 1
  
  if np.count_nonzero(served) == 13:
    finished = True

departure_timesA


Customer 0 has been served at 52
Customer 1 has been served at 84
Customer 2 has been served at 139
Customer 3 has been served at 187
Customer 4 has been served at 205
Customer 5 has been served at 255
Customer 6 has been served at 302
Customer 7 has been served at 320
Customer 8 has been served at 348
Customer 9 has been served at 402
Customer 10 has been served at 451
Customer 11 has been served at 527
Customer 12 has been served at 549


array([ 52,  84, 139, 187, 205, 255, 302, 320, 348, 402, 451, 527, 549])

## Version for part (B)

In [ ]:
availableA = True
availableB = True
clock = 0
currentTaskTimeA = -1
currentCustomerA = -1
currentTaskTimeB = -1
currentCustomerB = -1

served = arrival_times == 0 # logical array for served / not served
finished = False
backlog = np.zeros_like(service_times, dtype=int)
wait_times = np.ones_like(arrival_times) * -1

while not finished:
  clock += 1 # Process tick on the clock
  if currentTaskTimeA > 0:
    currentTaskTimeA -= 1
  if currentTaskTimeA == 0:
    served[currentCustomerA] = True
    print('Customer {} has been served at {} by A'.format(currentCustomerA,clock))
    departure_timesB[currentCustomerA] = clock

    if np.count_nonzero(backlog) > 0:
      currentCustomerA = np.argmax(wait_times)
      currentTaskTimeA = backlog[currentCustomerA]
      # print('Initiated Task #{} ({}) at time {}'.format(currentCustomer, currentTaskTime, clock))
      wait_times[currentCustomerA] = -1
      backlog[currentCustomerA] = 0

    else:
      currentCustomerA = -1
      currentTaskTimeA = -1
      availableA = True

  if currentTaskTimeB > 0:
    currentTaskTimeB -= 1
  if currentTaskTimeB == 0:
    served[currentCustomerB] = True
    print('Customer {} has been served at {} by B'.format(currentCustomerB,clock))
    departure_timesB[currentCustomerB] = clock

    if np.count_nonzero(backlog) > 0:
      currentCustomerB = np.argmax(wait_times)
      currentTaskTimeB = backlog[currentCustomerB]
      # print('Initiated Task #{} ({}) at time {}'.format(currentCustomer, currentTaskTime, clock))
      wait_times[currentCustomerB] = -1
      backlog[currentCustomerB] = 0

    else:
      currentCustomerB = -1
      currentTaskTimeB = -1
      availableB = True

  # Handle arrivals
  for customer in range(13):
    if clock == arrival_times[customer]:
      # print('Customer {} arrived at {}'.format(customer,clock))
      if availableB:
        currentCustomerB = customer
        currentTaskTimeB = service_times[customer]
        # print('Initiated Task#{} ({}) by B at {}'.format(currentCustomerB, currentTaskTimeB, clock))
        availableB = False
      else:
        if availableA:
          currentCustomerA = customer
          currentTaskTimeA = service_times[customer]
          # print('Initiated Task#{} ({}) by A at {}'.format(currentCustomerA, currentTaskTimeA, clock))

          availableA = False
        else:
          backlog[customer] = service_times[customer] # Add their service to the backlog
          wait_times[customer] = 0 # Initiate their waiting process
    

    if wait_times[customer] >= 0: # handle waiting
      wait_times[customer] += 1
  
  if np.count_nonzero(served) == 13:
    finished = True

departure_timesB


Customer 0 has been served at 52 by B
Customer 1 has been served at 63 by A
Customer 2 has been served at 118 by B
Customer 4 has been served at 136 by B
Customer 3 has been served at 143 by A
Customer 5 has been served at 204 by B
Customer 7 has been served at 239 by B
Customer 6 has been served at 245 by A
Customer 8 has been served at 332 by B
Customer 9 has been served at 400 by B
Customer 10 has been served at 451 by B
Customer 11 has been served at 527 by B
Customer 12 has been served at 549 by B


array([ 52,  63, 118, 143, 136, 204, 245, 239, 332, 400, 451, 527, 549])

## Version for Part C

In [ ]:
available = True
clock = 0
currentTaskTime = -1
currentCustomer = -1
served = arrival_times == 0 # logical array for served / not served
finished = False
backlog = np.zeros_like(service_times, dtype=int)
wait_times = np.ones_like(arrival_times, dtype=int) * -1
while not finished:
  clock += 1 # Process tick on the clock
  if currentTaskTime > 0:
    currentTaskTime -= 1
  if currentTaskTime == 0:
    served[currentCustomer] = True
    print('Customer {} has been served at {}'.format(currentCustomer,clock))
    departure_timesC[currentCustomer] = clock

    if np.count_nonzero(backlog) > 0:
      myArray = [(x,y) for x,y in enumerate(wait_times) if y >= 0]
      print(myArray)
      currentCustomer = max(myArray)[0]
      # print('Next up: ', currentCustomer)
      currentTaskTime = backlog[currentCustomer]
      # print('Initiated Task #{} ({}) at time {}'.format(currentCustomer, currentTaskTime, clock))
      wait_times[currentCustomer] = -1
      backlog[currentCustomer] = 0

    else:
      currentCustomer = -1
      currentTaskTime = -1
      available = True

  # Handle arrivals
  for customer in range(13):
    if clock == arrival_times[customer]:
      # print('Customer {} arrived at {}'.format(customer,clock))
      if available:
        currentCustomer = customer
        currentTaskTime = service_times[customer]
        # print('Initiated Task #{} ({}) at time {}'.format(currentCustomer, currentTaskTime, clock))
        available = False
      else:
        backlog[customer] = service_times[customer] # Add their service to the backlog
        wait_times[customer] = 0 # Initiate their waiting process
    

    if wait_times[customer] >= 0: # handle waiting
      wait_times[customer] += 1
  
  if np.count_nonzero(served) == 13:
    finished = True

departure_timesC


Customer 0 has been served at 52
[(1, 21)]
Customer 1 has been served at 84
[(2, 21)]
Customer 2 has been served at 139
[(3, 44), (4, 40)]
Customer 4 has been served at 157
[(3, 62), (5, 3)]
Customer 5 has been served at 207
[(3, 112), (6, 9)]
Customer 6 has been served at 254
[(3, 159), (7, 33)]
Customer 7 has been served at 272
[(3, 177)]
Customer 3 has been served at 320
[(8, 16)]
Customer 8 has been served at 348
[(9, 2)]
Customer 9 has been served at 402
Customer 10 has been served at 451
Customer 11 has been served at 527
Customer 12 has been served at 549


array([ 52,  84, 139, 320, 157, 207, 254, 272, 348, 402, 451, 527, 549])

In [ ]:
print('Departure Times (A) : ',departure_timesA)
print('Departure Times (B) : ',departure_timesB)
print('Departure Times (C) : ',departure_timesC)

Departure Times (A) :  [ 52  84 139 187 205 255 302 320 348 402 451 527 549]
Departure Times (B) :  [ 52  63 118 143 136 204 245 239 332 400 451 527 549]
Departure Times (C) :  [ 52  84 139 320 157 207 254 272 348 402 451 527 549]
