In [1]:
import numpy as np

A = np.array([[.95,.08,0],[0.05,0.87,0.08],[0,.05,.92]])
A

array([[0.95, 0.08, 0.  ],
       [0.05, 0.87, 0.08],
       [0.  , 0.05, 0.92]])

In [2]:
[evals,evecs] = np.linalg.eig(A)

In [3]:
evals

array([0.80675445, 1.        , 0.93324555])

In [4]:
evecs

array([[-0.45496212, -0.80498369, -0.77408722],
       [ 0.81464126, -0.5031148 ,  0.16211754],
       [-0.35967914, -0.31444675,  0.61196968]])

In [5]:
v = evecs[:,1]
sum(v)

-1.6225452416572228

In [8]:
v = v/sum(v)
v

array([0.49612403, 0.31007752, 0.19379845])

In [9]:
np.matmul(A,v)
# Expected to return v back to us

array([0.49612403, 0.31007752, 0.19379845])

In [26]:
print(np.linalg.matrix_power(A,10))
print('\n')
print(np.linalg.matrix_power(A,100))
print('\n')
print(np.linalg.matrix_power(A,500))


[[0.6989138  0.3899476  0.14686451]
 [0.24371725 0.40075653 0.3348734 ]
 [0.05736895 0.20929588 0.51826208]]


[[0.49649819 0.49599866 0.49536679]
 [0.30999916 0.31010378 0.31023611]
 [0.19350265 0.19389757 0.1943971 ]]


[[0.49612403 0.49612403 0.49612403]
 [0.31007752 0.31007752 0.31007752]
 [0.19379845 0.19379845 0.19379845]]


## Machine Problem

In [29]:
A = np.array([[0.9,0.6,0],
             [0.095,0.4,0],
              [0.005,0,1]])

np.linalg.matrix_power(A,365)@np.array([1,0,0])

array([0.17793232, 0.02837656, 0.79369112])

In [30]:
[evals,evecs] = np.linalg.eig(A)
print(evals)
print(evecs)

[1.         0.30431228 0.99568772]
[[ 0.          0.70964314 -0.64959358]
 [ 0.         -0.70454284 -0.10359688]
 [ 1.         -0.0051003   0.75319046]]
